Django/login/apps/login_reg/urls.py
from django.conf.urls import url
from . import views

app_name = 'login_app'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^register', views.register, name='register'),
	url(r'^login', views.login, name='login')
]

Django/login/login/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login_reg.urls', namespace='login_reg'))
]

Django/login/apps/login_reg/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import re
import bcrypt
from datetime import datetime
from django.db import models

# Create your models here.
class UserManager(models.Manager):
	def validate_email(self, email):
		email= {'valid':True}
		if not re.match(r('^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9]+\.[a-zA-Z0-9-.]+$')):
			email['valid'] = False
		
	def registervalidate(self, postData):
		results = {'status': True, 'errors': [], 'user': None}
		if not postData['userName'] or len(postData['userName']) < 2:
			results['status'] = False
			resutls['errors'].append('Username must be more than 2 characters')
		if not postData['email'] or email['valid'] == False:
			results['status'] = False
			results['errors'].append('email is not valid')
		if not postData['password'] or len(postData['password']) < 3:
			results['status'] = False
			results['errors'].append('Password is not long enough')
		if postData['conf_password']!=postData['password']:
			results['status'] = False
			results['errors'].append('Passwords do not match')
		if results['status'] is False:
			return results
		user = User.objects.filter(username=postData['userName'])
		if user:
			results['status'] = False
			results['errors'].append('No account under tha name is found')
		if results['status']:
			password = bcrypt.hashpw(postData['password'].encode(), bcrypt.gensalt())
			user = User.objects.create(
				username=postData['userName'],
				email=postData['email'],
				password=password)
			results['user'] = user
		return resutls

	def login(self, postData):
		results = {'status':True, 'errors':[], 'user': None}
		user = User.objects.filter(username=postData['userName'])
		try:
			user[0]
		except IndexError:
			results['status'] = False
			results['errors'].append('username or password is incorret')
			return results
		if user[0]:
			if user[0].password != bcyrpt.hashpw(postData['password'].encode(), user[0].password.encode()):
				results['status'] = False
				results['errors'].append('Invalid login')
			else:
				results['user'] = user[0].id
		else:
			results['status'] = False
		return results

class User(models.Model):
	userName = models.CharField(max_length=100)
	email = models.CharField(max_length=100)
	password =models.CharField(max_length=100)
	conf_password = models.CharField(max_length=100)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	
	def __str__(self):
		return str(self.id) + ', ' + self.userName
	objects = UserManager()

Django/login/apps/login_reg/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User
# Create your views here.
def index(request):
	#print '*********TEST******'
	if request.session.get('id'):
		return redirect('login_app:index')
	return render(request, 'login_reg/index.html')

def register(request):
	results = User.objects.registervalidate(request.POST)
	print "***UserResult, back in views ***", results['status']
	if not results['status']: 
		for error in results['errors']:
			messages.error(request, error)
			return redirect('login_app:index')
	request.session['id']=results['user'].id 
	return redirect('login_app:main')

def login(request):
	results = User.objects.login(request.POST)
	# results.request.POST(postData['username'], user.id)
	if results['status'] is False:
		for error in results['errors']:
			messages.error(request, error)
		return redirect('login_app:index')
	else:
		user = User.Objects.get(id=results['user'])
		request.session['id']=user.id 
	return redirect('login_reg/main.html')

Django/login/apps/login_reg/templates/login_reg/index.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Login</title>
    </head>
    <body>
    <h1>Login</h1>
     <form action="{% url 'login_reg:login' %}" method="post">
     	{% csrf_token %}
      	Username: <input type="text" name="userName" value=""/>
      	Password: <input type="text" name="password" value=""/>
      	<input type="submit" name="submit" value="submit"/>
      </form>
      <h1>Register</h1>
      <form action="{% url 'login_reg:register' %}" method="post">
      	{% csrf_token %}
      	Username: <input type="text" name="userName" value=""/>
      	Email: <input type="text" name="email" value=""/>
      	Password: <input type="password" name="password" value=""/>
      	Confirm Password: <input type="password" name="conf_password" value=""/>
      	<input type="submit" name="submit" value="submit"/>
      </form>
    </body>
</html>

Django/login/apps/login_reg/templates/login_reg/main.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Untitled</title>
    </head>
    <body>
      <h1>Welcome</h1> 
    </body>
</html>