Django/myBook/apps/login/urls.py
''' App URLS.py file. '''
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
]

Django/myBook/apps/my_book/urls.py
from django.conf.urls import url
from.import views

app_name = 'mybook'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^addBlog$', views.addBlog, name='addBlog'),
    url(r'^addLike$', views.addLike, name='addLike'),
]

Django/myBook/myBook/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^mybook/', include('apps.my_book.urls', namespace='mybook')),
]

Django/myBook/apps/my_book/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from ..login.models import User


# Create your models here.
class BlogManager(models.Manager):
    def addBlog(self, postData):
        results = {'status': True, 'errors': []}
        if len(postData['title']) < 1 and len(postData['content']) < 1:
            results['errors'].append('All fields must be filled out')
            results['status'] = False

        user = User.objects.get(id=postData['user_id'])
        if results['status']:

            try:
                blog = Blog.objects.create(
                    title=postData['title'],
                    content=postData['content'],
                    user_id=user,
                )
                blog.save()
            except:
                results['errors'].append('Error: Blog not created')

        return results

    def addLike(self, postData, user_id):
        results = {'status': True, 'errors': []}
        try:
            print 'mskjsdkjskdksjksdjksdjksjksdjskjdkjsdkj'
            blog = Blog.objects.get(postData['blog_id'])
            user = User.objects.get(id=user_id)
            like = Blog.likedBlogs.add(user)
            blog.save()
        except:
            results['errors'].append('Error: not liked')

        return results


class Blog(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=5000)
    user_id = models.ForeignKey('login.User', related_name='blogs')
    likes = models.ManyToManyField('login.User', related_name='likedBlogs')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = BlogManager()

Django/myBook/apps/my_book/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from .models import Blog, User


# Create your views here.
def index(request):

    if not checkAuth(request):
        return redirect('/')

    user = User.objects.get(id=request.session.get('id'))
    blogs = Blog.objects.all().order_by('-created_at')[:5]
    context = {
        'user': user,
        'blogs': blogs,
    }
    return render(request, 'my_book/index.html', context)


def addBlog(request):
    print 'kjdksjdkjskdjskjskj'
    if not checkAuth(request):
        return redirect('/')

    if request.POST:
        results = Blog.objects.addBlog(request.POST)
        if results:
            messages.info(request, 'Blog Added')
        else:
            for error in results:
                messages.error(request, error)
            return redirect('mybook:addBlog')
        return redirect('mybook:index')

    user = User.objects.get(id=request.session.get('id'))
    context = {
        'user': user,
    }
    return render(request, 'my_book/addBlog.html', context)


def addLike(request):
    if request.POST:
        results = Blog.objects.addLike(request.POST, request.session['id'])
        if results:
            messages.info(request, 'Liked!')
        else:
            for error in results:
                messages.error(request, error)
        return redirect('mybook:index')


def checkAuth(request):  # Force non-authorized user back to login/registration page
    try:
        if not request.session.get('id'):
            messages.error(request, 'NO.')
            return False
        return True
    except:
        messages.error(request, 'NO')
        return False

Django/myBook/apps/my_book/templates/my_book/addBlog.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Add Blog</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/style.css" rel="stylesheet">
    </head>
    <body>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
        <form action="{% url 'mybook:addBlog' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="title" placeholder="Enter Blog Title" autofocus><br>
            <textarea name="content" rows="5" cols="50"></textarea><br>
            <input type="hidden" name="user_id" value="{{user.id}}">
            <button type="submit" name="submit" value="submit">Add!</button>
        </form>    
    </body>
</html>

Django/myBook/apps/my_book/templates/my_book/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>My Blog</title>
        <meta charset="UTF-8">
    </head>
    <body>
        {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        <a href="{% url 'mybook:index' %}">Home</a>
        <a href="{% url 'mybook:addBlog' %}">Add Blog</a>
        <a href="{% url 'login:logout' %}">Logout</a>
    <h1>{{user.username}}'s Blogs</h1>
    {% for blog in blogs %}
    <div>
        <h1>{{blog.title}}</h1>
            Created: {{blog.created_at}}
        <div>
            {{blog.content}}<br>
            {{blog.likes.all.count}} liked this!
            {% if blog.user_id != user %}
                <form action="{% url 'mybook:addLike' %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" name="submit" value="submit">Like!</button>
                    <input type="hidden" name="blog_id" value="{{blog.id}}">
                </form>
            {% endif %}
        </div>
    {% endfor %}
    <h3></h3>
    </body>
</html>